### ISSUE TITLE
Hyperbolic Generator -- Returning Embedding Information

### ISSUE THREAD

**Issue by lacoperon** [kit-parco/networkit#137]
Hi there,

I'm trying to extend the functionality of the HyperbolicGenerator code found in [cpp/generators/HyperbolicGenerator.cpp](https://github.com/kit-parco/networkit/blob/Dev/networkit/cpp/generators/HyperbolicGenerator.cpp) . The code itself (starting with the `generate` function) generates two vectors (`angles` and `radii`) describing polar coordinates corresponding to the angular and radial coordinates of each point within the randomly generated hyperbolic graph.

It then uses those coordinates (with some smart heuristics outlined within [this paper](https://arxiv.org/pdf/1606.09481.pdf) for the T=0 case I'm working with) to determine if two nodes are linked based on the hyperbolic distance between the nodes ( P(connection) goes to 1 as the distance between the nodes goes to 0 )

Currently, the code just returns the NetworKit `Graph` object generated by this process, without any information about where the nodes exist within the hyperbolic space, and I want to modify the code so it returns the `angles` and `radii` vectors associated with each point in the generated graph (I'm doing research related to greedy routing, so this information is helpful).

I could just modify the Cython code to export as a csv the two vectors for each node, but I'm sure there are other use cases in which returning embedding information from graphs generated within NetworKit would be useful. 

To that end, is there a canonical way to write this out for NetworKit generators, and would that be a worthwhile contribution? Should I add a boolean parameter specifying whether or not the embedded polar coordinates should be returned?

Thanks

**Comment by hmeyerhenke** [comment]
Hi Elliot,

Not all generators produce graphs that live within some geometric space. Thus, when passing back this kind of information, it should always be optional. (People generating geometric graphs may not be interested in the coordinates, either.)

My suggestion would be to write an additional getter for the coordinate information. This would be consistent with other algorithms. Call run() for the main algo, then call a getter for retrieving the info you are interested in.

Moritz, Kolja, and Alexander can assist with further technical details (Moritz because he wrote the hyperbolic generator in the first place).

Best,
Henning

**Comment by mlooz** [comment]
Hi Elliot,

the functionality you describe is present in the DynamicHyperbolicGenerator class, which accepts the same arguments. Just call the method getCoordinates(), which is also exposed in Cython.

All the best,
Moritz
