### ISSUE TITLE
Test failure in testHashingOverlapperForCorrectness

### ISSUE THREAD

**Issue by avdgrinten** [kit-parco/networkit#175]
After the merge of #170, one of the tests fails on CI. It did not fail on the PR's branch; the failure might have been caused by the merge. @rbange can you look into that?

**Comment by rbange** [comment]
Yea, indeed this is caused by https://github.com/kit-parco/networkit/pull/159 which somehow changes the order of elements in the output partition of the `HashingOverlapper::run` method. Because https://github.com/kit-parco/networkit/pull/159 was not merged into https://github.com/kit-parco/networkit/pull/170, the test failed. 
I rebased my branch and fixed the assertion in https://github.com/kit-parco/networkit/pull/176

**Comment by avdgrinten** [comment]
Thank you.
