### ISSUE TITLE
ConnectedComponents broken?

### ISSUE THREAD

**Issue by mocnik-science** [kit-parco/networkit#193]
I execute the following code:
```python
from networkit import *
g = generators.ErdosRenyiGenerator(100, .5).generate()
components.ConnectedComponents(g).run().getPartition()
```
I get the following error:
```
Python(43136,0x7fff959ca380) malloc: *** error for object 0x7fb1e16ca220: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Anyone else experiencing the same issues?

Any idea why this does not work?

**Comment by eug93** [comment]
This is probably due to the Cython destructor of ConnectedComponents. When you call:

`components.ConnectedComponents(g).run().getPartition()`

the instance of ConnectedComponents is immediately destroyed after the call to `getPartition()`.
The `ConnectedComponents` class inherits from the `Algorithm` abstract class and both classes have a `__dealloc__` method. Probably, both of them are called and since the `__dealloc__` implementation of `ConnectedComponents` does not do any check before trying to destroy the instance, then you get the error.

A temporary solution to this could be to split your code like this:

```
from networkit import *
g = generators.ErdosRenyiGenerator(100, .5).generate()
cc = components.ConnectedComponents(g).run()
partition = cc.getPartition()
```

**Comment by eug93** [comment]
A patch that fixes this issue has just been merged into the Dev branch.
