### ISSUE TITLE
OpenMP and clang travis setup

### ISSUE THREAD

**Issue by michitux** [kit-parco/networkit#2]
I'm currently trying to reproduce the segfault in the LFR test case ([see Job #6.3](https://travis-ci.org/kit-parco/networkit/jobs/198574045)). Unfortunately I'm unable to reproduce it locally. While comparing the setup I noticed two things:

* travis is using clang 3.7 without OpenMP support
* travis uses the trunk version (i.e., the current development version) of the OpenMP library of clang

Locally, I have clang 3.9.1 which includes OpenMP support.

Just to exclude the possibility that the crash is due to some bug in the current development branch of OpenMP - is there anything that speaks against using at least a stable version of the OpenMP support library or directly switch to at least clang 3.8 which includes OpenMP support?

**Comment by kolja-esders** [comment]
I would say it depends which version of clang we want to officially support.

Wouldn't mind switching to >= 3.8 directly just not sure whether we have any commitments to support 3.7. @hmeyerhenke?

Using a stable version of OpenMP as a starting point makes sense.

**Comment by hmeyerhenke** [comment]
Am 06.02.17 um 16:15 schrieb Kolja Esders:
> I would say it depends which version of clang we want to officially support.
> 
> Wouldn't mind switching to >= 3.8 directly just not sure whether we have
> any commitments to support 3.7. @hmeyerhenke
> <https://github.com/hmeyerhenke>?

I've never worked with clang, so that I don't see a reason why to
support a version that does not work for us. I would say switch to
something that works.

NB: Supporting older compilers is often necessary to let code run on
compute servers and HPC machines (that do not always support the newest
versions). I don't think clang is heavily used for this purpose anyway,
at least not on the machines I use.


> 
> Using a stable version of OpenMP as a starting point makes sense.

Yes.

**Comment by kolja-esders** [comment]
Updated Travis config. Not perfect yet but segfaults are resolved.
