### ISSUE TITLE
Reduce test execution time

### ISSUE THREAD

**Issue by kolja-esders** [kit-parco/networkit#7]
Make sure all tests run in a reasonable amount of time (<< 1s per test) if possible.
This might be accomplished by
* Adjusting the parameters of the algorithms
* Reducing/Eliminating the use of external graph files (except for read/write tests)

**Comment by hmeyerhenke** [comment]
I would not discourage the use of external graph files per se. If they are too big, however, they should be replaced by smaller ones.

**Comment by kolja-esders** [comment]
Good point.

Thoughts on "tests" like [these](https://github.com/kit-parco/networkit/blob/dd2b64353c32c9516949d5f9970bdd18cc1359b4/networkit/cpp/centrality/test/CentralityGTest.cpp#L473)?

Would either like to remove those or clearly express the intent (through asserts) of a test. Just executing a method without even asserting for an exception (which I presume was the intention here) doesn't make sense to me.

**Comment by hmeyerhenke** [comment]
You are right in that this is not a proper test without assertions. I discourage complete removal, though. If it is too difficult to find meaningful assertions (e.g. because you did not write the code), then change from test* to try* to indicate that this part needs more work.

**Comment by kolja-esders** [comment]
@ebergamini Could you take a look at [these tests](https://github.com/kit-parco/networkit/blob/dd2b64353c32c9516949d5f9970bdd18cc1359b4/networkit/cpp/centrality/test/DynBetweennessGTest.cpp)?

There are no asserts/expects in there. Also do you think it is fine to replace the graph with a smaller one like jazz to reduce the runtime?

**Comment by michitux** [comment]
Maybe the assertions are in the called code itself (using `assert`)? And maybe they are only triggered with large enough or special instances?

Note that currently, assertions are off in the builds on travis. I would suggest to turn them on for tests.

**Comment by hmeyerhenke** [comment]
Clarification: When I said assertions, I meant "assert" and "EXPECT".

**Comment by kolja-esders** [comment]
We can probably still differentiate between asserts in the code itself and the tests on top of that. I feel like the former is basically designed to be a coded comment describing the intended states the author is expecting. In contrast the tests can be used to ensure the correctness of one specific functionality at a time.

So I would argue to only have tests that contain the minimal number of assertions needed to ensure a specific functionality/feature is working as intended.

Just by quickly glancing at the code I found a couple of asserts but as far as I can see those are not directly related to the size of the instance. Would still be nice to get the confirmation from Elisabetta.

**Comment by michitux** [comment]
Sometimes it is really difficult to write a test that really tests the functionality/feature because the tested algorithm is heuristic, randomized and parallel. Note that heuristic and randomized wouldn't be that much of a problem as we can fix the seed of the random number generator (a feature definitely not used enough yet in the tests), but parallelism sometimes really means you have no possibility to get reproducible results. Therefore, testing the result of such an algorithm will always lead to random test failures (as we can already see them, see e.g. #6). However, internal assertions may at least verify that certain internal invariants are fulfilled and therefore provide at least some level of testing. I have no idea if this is indeed the case with the tests you mentioned, I just wanted to give an explanation why it might be okay that some tests just execute an algorithm without testing the result (though maybe a comment mentioning this could be added to these test cases).

**Comment by hmeyerhenke** [comment]
Okay. But even a parallel algorithm should produce a result that has _some_ testable properties.

**Comment by kolja-esders** [comment]
I definitely agree with you on the issue of having a lot of tests that currently fail randomly because of missing seeds.

Apart from that I am not sure about whether it is really hard to test parallel algorithms. In the end we don't care about how an algorithm is implemented but to which results it leads.

In case parallelism in the implementation leads to a higher variance in the result space then we should consciously decide whether that is okay with us and which boundaries we regard as acceptable for the result.
Then we specify those boundaries in the test and if the test fails it actually means that this is a real problem and needs to be addressed.

So either our boundaries are too strict and we would accept looser boundaries (in which case we need to adjust the tests) or the boundaries are what we want and the implementation cannot guarantee those boundaries in which case the implementation needs to change.

Not sure whether this is your main concern when testing parallel implementations.

**Comment by ebergamini** [comment]
Hi Kolja,

yes, in the case you mentioned the asserts are only in the code itself. It’s hard to write expects in the test because it’s an approximation algorithm and the only thing we know is that with some probability the approximation will be within a certain interval.
It shouldn't be a problem to replace PGP with a smaller graph, though.
Best,

Elisabetta
