### ISSUE TITLE
windows install networkit via pip always errors

### ISSUE THREAD

**Issue by CLWcynthia** [kit-parco/networkit#82]
i use python3.6.1 and install minGW gcc version 7.2.0,but pip install networkit error

C:\Users\chen>pip install networkit
Collecting networkit
Using cached networkit-4.4.tar.gz
Complete output from command python setup.py egg_info:
'pip3' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Requirement already satisfied: ipython in d:\anaconda\lib\site-packages
Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\chen\AppData\Local\Temp\pip-build-p4lcwpal\networkit\setup.
py", line 127, in 
cppcompiler, stdflag = determineCompiler(candidates, ["c++14","c++11"])
File "C:\Users\chen\AppData\Local\Temp\pip-build-p4lcwpal\networkit\setup_
util.py", line 149, in determineCompiler
os.remove("test_build")
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'test_build'

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\chen\App
Data\Local\Temp\pip-build-p4lcwpal\networkit\

**Comment by kolja-esders** [comment]
Hi CLWcynthia,

during compilation the setup checks whether you have a compatible C++ compiler installed by building a test source file. Apparently, the compilation process (using g++) returned `0` (indicating success) while still not generating the output file (named **test_build**).

You could try to compile the sample source file manually and take a look at the output and whether the output file was generated for a first analysis. If you try this it would be great if you could let us know what the output of the compilation process is so that we can adjust the code accordingly. Below you can find the source code.

I should also note that we do not offer full Windows support at this point in time. Using our virtual machine which you can find [here](https://networkit.iti.kit.edu/uploads/networkit-vm.zip) might be easier if that is an option for you.

```
	/*****************************************************************************
	* File: sample.cpp
	* DESCRIPTION:
	*   OpenMP Example - Hello World - C/C++ Version
	*   In this simple example, the master thread forks a parallel region.
	*   All threads in the team obtain their unique thread number and print it.
	*   The master thread only prints the total number of threads.  Two OpenMP
	*   library routines are used to obtain the number of threads and each
	*   thread's number.
	* AUTHOR: Blaise Barney  5/99
	* LAST REVISED: 04/06/05
	******************************************************************************/
	#include <omp.h>
	#include <iostream>

	[[deprecated("use the function body directly instead of wrapping it in a function.")]]
	void helloWorld() {
		std::cout << "Hello world" << std::endl;
	}

	int main (int argc, char *argv[]) {
		helloWorld();
		int nthreads, tid;
		/* Fork a team of threads giving them their own copies of variables */
		#pragma omp parallel private(nthreads, tid)
		{
			/* Obtain thread number */
			tid = omp_get_thread_num();
			std::cout << \"Hello World from thread = \" << tid << std::endl;
			/* Only master thread does this */
			if (tid == 0) {
				nthreads = omp_get_num_threads();
				std::cout << \"Number of threads = \" << nthreads << std::endl;
			}
		}  /* All threads join master thread and disband */
	}

```
