### ISSUE TITLE
Cannot represent MultiDiGraphs

### ISSUE THREAD

**Issue by TobiasSkovgaardJepsen** [kit-parco/networkit#87]
I am doing a machine learning project on a road network and have been unable to find a suitable replacement for the networkx MultiDiGraph type. In the road network from OpenStreetMap that I am using legitimate multi-edges occurs.

As far as I can tell, there is no way to distinguish two (parallel) edges with the same source and target nodes in NetworKit which becomes problematic when I need to associate attributes with such edges.

**Comment by hmeyerhenke** [comment]
This is correct. Multigraphs are not supported natively in NetworKit. It
is one of the choices we had to make at some point. Back then, multigraphs did not present a major use case for the NetworKit community.

Changing this now would mean a lot of work since not only the graph data structure, but also many algorithms would have to be checked for consistency.
